# This file was generated by GoReleaser. DO NOT EDIT.
cask "sarj" do
  version "1.2.0"

  on_macos do
    on_intel do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_darwin_amd64.tar.gz"
      sha256 "23b9d782779006d4c7ebf2778c5de8e49097c9f77f2a8e6ab24f5cfd10ddf0d4"
    end
    on_arm do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_darwin_arm64.tar.gz"
      sha256 "12c25ab7e38e289a058e9e2c41da40e47d8ed36b97bf15d3ba217e3ea5938457"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_linux_amd64.tar.gz"
      sha256 "01746b11211c3446040dfd4da2a103507caa9684a2b3a01077a569e5f406196d"
    end
    on_arm do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_linux_arm64.tar.gz"
      sha256 "5591d9463e747a22687698d9c56621ef105f34a535faaf11a62569b9c3a46d07"
    end
  end

  name "sarj"
  desc "Git worktree + tmux session manager"
  homepage "https://github.com/davidmks/sarj"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sarj"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sarj"]
  end

  # No zap stanza required

end
