# This file was generated by GoReleaser. DO NOT EDIT.
cask "sarj" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "3e6b0368f728c8df8775ba91028e10fe3d3e6f049a783765cf49532f955aa52d"
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4830db7acbe65b824a6e8d091d5d179f3afe621a579b04f6e685845582383e18"
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "54f241fe1aca9dea2dda8fac88678974870c46e8f3f620365151dc184ddd5259"
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76cca883987fdb6aea5e63ea3d73f1f16d0755e68c782df75b1a1832e1cd8158"
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sarj"
  desc "Git worktree + tmux session manager"
  homepage "https://github.com/davidmks/sarj"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sarj"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sarj"]
  end

  # No zap stanza required
end
