# This file was generated by GoReleaser. DO NOT EDIT.
cask "sarj" do
  name "sarj"
  desc "Git worktree + tmux session manager"
  homepage "https://github.com/davidmks/sarj"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sarj"

  on_macos do
    on_intel do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_darwin_amd64.tar.gz"
      sha256 "fc626a5871e68583ecb69cd912117efec44047a4a6a53f2041c4058d0625f65e"
    end
    on_arm do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_darwin_arm64.tar.gz"
      sha256 "c27c60f63558e3881df181baf88ae94c9a0917d85aaef7ff848e4a589164d103"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_linux_amd64.tar.gz"
      sha256 "81dcf791b03767f715a13f3e9275d9f9ff1a52d261f618785148b69c94deb6d8"
    end
    on_arm do
      url "https://github.com/davidmks/sarj/releases/download/v#{version}/sarj_#{version}_linux_arm64.tar.gz"
      sha256 "5ff652e08ff819ab143a4e021173101c48473b86b9408c023a2909ad87e16ba1"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sarj"]
  end

  # No zap stanza required
end
